application: sandbox4sinmetal-tg
module: simple-gae
version: 201408021343
runtime: go
api_version: go1

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic  # default value


handlers:
- url: /webroot
  static_dir: webroot

- url: /.*
  script: _go_app
  login: required